Models/ErrorViewModel.cs
using System;

namespace SuperHero.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperHero.Models
{
    public class Superhero
    {
        [Key]
        public int SuperheroId { get; set; }
        public string Name { get; set; }
        public string AlterEgo { get; set; }
        public string PrimarySuperheroAbility { get; set; }
        public string SecondarySuperheroAbility { get; set; }
        public string Catchphrase { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperHero.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SuperHero.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SuperheroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperHero.Data;
using SuperHero.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperHero.Controllers
{
    public class SuperheroController : Controller
    {
        private ApplicationDbContext _context;

        public SuperheroController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: SuperheroController
        public ActionResult Index()
        {
            var superhero = _context.Superheroes.ToList();
            return View(superhero);
        }

        // GET: SuperheroController/Details/5
        public ActionResult Details(int id)
        {
            var superhero = _context.Superheroes.Where(e => e.SuperheroId == id).FirstOrDefault();
            return View(superhero);
        }

        // GET: SuperheroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SuperheroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Superhero superhero)
        {
            try
            {
                _context.Superheroes.Add(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperheroController/Edit/5
        public ActionResult Edit(int id)
        {
            var superhero = _context.Superheroes.Where(e => e.SuperheroId == id).FirstOrDefault();
            return View(superhero);
        }

        // POST: SuperheroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Superhero superhero)
        {
            try
            {
                
                _context.Superheroes.Update(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperheroController/Delete/5
        public ActionResult Delete(int id)
        {
            var superhero = _context.Superheroes.Where(s => s.SuperheroId == id).FirstOrDefault();
            return View(superhero);
        }

        // POST: SuperheroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Superhero superhero)
        {
            try
            {
                
                _context.Superheroes.Remove(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Superheroes!</h1>
    <p> Here is one of my favorite superheroes</p>
    <img src="https://www.thewrap.com/wp-content/uploads/2016/05/Wolverine4-1.jpg" alt="Hugh Jackman Would&#39;ve Played MCU Wolverine Had Timing Been Right"/>"
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperHero</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperHero</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Create">Create Superhero</a>
                        </li>      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Index">List Of Superheroes</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SuperHero - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Superhero/Create.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimarySuperheroAbility" class="control-label"></label>
                <input asp-for="PrimarySuperheroAbility" class="form-control" />
                <span asp-validation-for="PrimarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondarySuperheroAbility" class="control-label"></label>
                <input asp-for="SecondarySuperheroAbility" class="form-control" />
                <span asp-validation-for="SecondarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Superhero/Delete.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimarySuperheroAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimarySuperheroAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondarySuperheroAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondarySuperheroAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catchphrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catchphrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SuperheroId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Superhero/Details.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimarySuperheroAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimarySuperheroAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondarySuperheroAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondarySuperheroAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catchphrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catchphrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SuperheroId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Superhero/Edit.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SuperheroId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimarySuperheroAbility" class="control-label"></label>
                <input asp-for="PrimarySuperheroAbility" class="form-control" />
                <span asp-validation-for="PrimarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondarySuperheroAbility" class="control-label"></label>
                <input asp-for="SecondarySuperheroAbility" class="form-control" />
                <span asp-validation-for="SecondarySuperheroAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Superhero/Index.cshtml
@model IEnumerable<SuperHero.Models.Superhero>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-danger">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
    @Html.DisplayNameFor(model => model.Name)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlterEgo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimarySuperheroAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondarySuperheroAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Catchphrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action ="details"asp-route-id ="@item.SuperheroId"> @Html.DisplayFor(modelItem => item.Name)</a>

</td>
            <td>
                @Html.DisplayFor(modelItem => item.AlterEgo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrimarySuperheroAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondarySuperheroAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catchphrase)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SuperheroId" class="btn btn bg-danger">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SuperheroId" class="btn btn bg-danger">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SuperheroId" class="btn btn bg-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>